version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
          composer install
          composer update
          ./vendor/bin/phpunit UnitTests.php