version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: Composer Install
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Vender Install
          command: |
            composer install
            composer update
      - run:
          name: Unit Tests
          command: |
            ./vendor/bin/phpunit UnitTests.php