version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - command: |
          composer install
          composer update
          ./vendor/bin/phpunit UnitTests.php