version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: Add jq dependency
          command: |
            curl -sS https://getcomposer.org/installer | php mv composer.phar /usr/local/bin/composer
            composer install
            composer update
